### ISSUE TITLE
Successful payment not detected by PrestaShop at all

### ISSUE THREAD

**Issue by rfc2822** [wirecard/prestashop-wcs#10]
Hello,

I have the following configuration:
PrestaShop 1.6.1.9 (not used in production yet)
WireCard plugin: git master from 22 Nov 2016 (with patched guzzle-http, see #4)

Successful payments are not detected by PrestaShop at all.

Steps to reproduce:
1. Install WireCard plugin in demo mode (configuration: Demo) for testing.
1. Do a checkout and make sure the customer birthday is set (to avoid issue #9).
1. For instance, select SOFORT banking as the payment method.
1. After clicking "Order with obligation to pay", the SOFORT demo page appears and allows to set Failure or Success.
1. Click "Success" to signal a successful payment.
1. You're returned to the PrestaShop, but it says "You haven't done any orders yet". When looking in the admin backend, there is no order.

Expected result:
The order should be registered by PrestaShop when a payment has been completed.

**Comment by jakubpolomsky** [comment]
Hello, I am having troubles trying to reproduce the issue. Could you provide some more details?

Steps I tried to reproduce your issue:
1. Download prestashop 1.6.1.9
2. Install prestashop 1.6.1.9
3. Download plugin from github
4. upload via plugin manager
5. select demo as testing environment
6. register an user
7. make an order with registered user
8. select sofort
9. click success
10. return to the shop with following message

> Thank you for your order.
> 
> Your order will soon be shipped.
> 
> For any questions or further information contact our customer support. 

In the backend of the shop the order status is **Payment accepted**

Is there anything else you did, that you got that status?

**Comment by rfc2822** [comment]
I have tried again with the birthday patch, and it has worked. If the problem occurs again, I'll try to post more information / steps to reproduce with a clean shop here.

**Comment by jakubpolomsky** [comment]
Thank you! I will close this issue then. If you find anything new, please feel free to open another issue.
